### ISSUE TITLE
Any way to load an external CSS as part of the theme

### ISSUE THREAD

**Issue by earnaway** [danielgtaylor/aglio#168]
If I try to run this:
`aglio.js --theme-style default --theme-style style.css -i file.apib -o output.html`
then it works well with the style.css file being imported
However, I'd like to load an external css file, ie:
`aglio.js --theme-style default --theme-style http://domain.com/style.css -i file.apib -o output.html`
but that fails.
Any chance that could be supported?

**Comment by danielgtaylor** [comment]
@earnaway is there a reason you can't just download the style before running Aglio? E.g. something like:

```sh
curl -O http://domain.com/style.css
aglio --theme-style default --theme-style style.css -i file.apib -o output.html
```

Alternatively, if you do not mind linking to the style directly you can create a small CSS file with an import statement and pass that into Aglio:

```css
@import url("http://domain.com/style.css");
```

Just note that the `@import` doesn't get replaced - your HTML output will contain that statement and the browser does the fetching on page load.

**Comment by earnaway** [comment]
Hi @danielgtaylor - that would work, however the server I'm testing this on doesn't serve static files or assets, just the root index controller, so can't add any other files, which is why I was hoping to include an external css file directly in the html, like you have:
`@import url("http://domain.com/style.css");`

**Comment by danielgtaylor** [comment]
@earnaway not sure if this is still an issue, but I suggest you do the following:

1. Create a file `style.css` with the following:

  ```css
  @import url("http://domain.com/style.css");
  ```

2. Call Aglio like `aglio --theme-style default --theme-style style.css -i input.apib -o output.html` and then serve the resulting single file.

Let me know if that doesn't work for you! I'm going to close this issue because I do not plan to support URLs as imports in the `--theme-style` parameters.
