### ISSUE TITLE
Cache assets locally for offline developing

### ISSUE THREAD

**Issue by moul** [danielgtaylor/aglio#17]
Do you manage to add this ?

Is using a custom theme with local assets a good alternative for you ?

**Comment by vincentriemer** [comment]
Any word/updates on this?

**Comment by danielgtaylor** [comment]
Please see my comment here: https://github.com/danielgtaylor/aglio/issues/33#issuecomment-70533061

**Comment by danielgtaylor** [comment]
This is mostly implemented in the new theme, so I'm going to close this. The only exception is that fonts are not cached, so you will get whatever system font is installed on your machine instead of the nice fonts. This should be fine for local development offline, then when you go online you'll get the fonts as well.
