### ISSUE TITLE
title disappear in three column theme

### ISSUE THREAD

**Issue by jk2K** [danielgtaylor/aglio#191]
![image](https://cloud.githubusercontent.com/assets/4025839/11029561/cc532fcc-8702-11e5-875a-595c58f5d96a.png)
the title disappears when mouse move in and out ¶

**Comment by danielgtaylor** [comment]
@jk2K I've noticed this as well. It must be some browser bug or CSS issue. I'm not sure what the problem is but will try to look into it.

**Comment by danielgtaylor** [comment]
@jk2K I've just released `olio-theme-1.4.1` which fixes this, along with a few other minor issues. Please take a look.

Unfortunately I believe there is a browser bug involved and I can't track down a way to fix it. The problem occurs because of the `.content` CSS rule, which has a `position: relative;` rule in it for the three column theme. When I remove that particular rule, the titles no longer disappear after hover. As a workaround (since I can't easily fix this myself) is to always show the title permalinks in the three column theme at a reduced opacity. Please let me know what you think and if you have any other workaround ideas!
