### ISSUE TITLE
Is the project dead?

### ISSUE THREAD

**Issue by sangar82** [danielgtaylor/aglio#258]
no more commits from 4 months ago... is the project dead?

**Comment by kiriakos-monday** [comment]
I'm not an authority here but I'd say aglio is stable, not dead. :-) 

Also, if You take a look at the network graph You'll see there is a lot going on in the forks.

**Comment by danielgtaylor** [comment]
@sangar82 It's not dead! I've just been insanely busy and there's been no time at work for Aglio due to other competing priorities. Expect some movement in the project soon, even if it's just to make sure we're using the latest parser. This is one of my favorite projects to work on and I haven't forgotten about it!

**Comment by sangar82** [comment]
Great!  I'm using aglio a lot and I want to continue using it! Thanks for your job and thanks for don't to forget it!@danielgtaylor !!

**Comment by Kyslik** [comment]
Are we operational? :)

**Comment by sangar82** [comment]
The same question one year later:

@danielgtaylor Is the project dead? 

Thanks!

**Comment by hurrycaner** [comment]
@danielgtaylor is the project dead? There are more than 2 years old open PRs...
Can't you ask for community to help you with maintenance?

**Comment by kylef** [comment]
There is a NOTE in the README mentioning that the project is searching for maintainers: https://github.com/danielgtaylor/aglio/commit/0cef09ab83d680689bcadf53aa45fc7bca3b5af3
