### ISSUE TITLE
Output html that can be opened directly in the browser (without a server)

### ISSUE THREAD

**Issue by odyssomay** [danielgtaylor/aglio#33]
It would be really nice for other developers if they could view the api without starting a server. Starting a server creates an extra step that is annoying and a little scary (for other people).

It does seem like the layout I'm using right now (`default-multi`) is working perfectly without a server. The only problem is that there's a huge banner saying `This page may not display correctly when opened as a local file. Instead, view it from a web server.`, which can't be closed. If it could be closed, it would pretty much fix this issue. I would prefer a more general solution where aglio can output files that can be viewed without a server though.

**Comment by arvenil** [comment]
+1 on merging those changes into upstream. I was really surprised that I was unable to open generated html without running a webserver.

**Comment by danielgtaylor** [comment]
There are some changes in the works to make the theme support a bit more flexible, and along with that I'm trying to address a lot of the user feedback like offline support. Part of that process is splitting the theme rendering from the main Aglio binary along with switching to local javascript and CSS. As a side effect and due to some new caching, the new stuff I'm working on is also much faster to render. I don't have an ETA yet, but it's coming soon and I'm working hard to keep it all backward compatible.

**Comment by moul** [comment]
Awesome, thanks !

**Comment by odyssomay** [comment]
Sounds good! :+1:

**Comment by mitchiru** [comment]
Awesome! Keep up the good work.

**Comment by onkami** [comment]
I actually wonder why explicit protocol is not used in URLs used in themes. I think the protocol of all these fontawesome and jquery CDNs is pretty much more fixed than the address and version of a library.

**Comment by danielgtaylor** [comment]
The latest updates to what is becoming Aglio 2.0.0 now supports this, so I'm going to close the issue. The new release is coming very soon.
