### ISSUE TITLE
Choices: [object Object]

### ISSUE THREAD

**Issue by mansona** [danielgtaylor/aglio#91]
I'm using the experimental branch for this because I'm using iojs but when I have the following input 

```
+ Parameters
    + type ( required, string, `bio`)
        + Values
            + `bio`
            + `other`
```

It produces the following output: 
```
type
string (required) Example: bio
Choices: [object Object], [object Object]
```
Image: https://cloudup.com/cIrncLeqghi

I've tried all different formats i could think of for those values (i'm new to api-blueprint) but nothing is working. 

Any suggestions?

**Comment by danielgtaylor** [comment]
There's an [example](https://raw.githubusercontent.com/danielgtaylor/aglio/master/example.md) that includes a list of choices. Just search the document for the word `sort`.

I'll need to install iojs and test on it. A quick test on Node 0.10 shows that your example **does work**. It's likely a bug related to iojs support or a breaking change in the output of the Blueprint AST produced by the parser. I'm going to look into this as soon as I can.

@zdne did the AST output change in a non-backwards-compatible way for Protagonist 0.18.x?

**Comment by zdne** [comment]
@danielgtaylor No, parameters part of the AST should be intact.

To verify I have just tested stable protagonist and experimental one with: 

```markdown
# R [/r{?type}]
## GET
+ Parameters
    + type
        + Values
            + `bio`
            + `other`

+ Response 200
```

and as you can see from the diff they are the same (left is the stable version)

![screen shot 2015-03-24 at 9 37 38 am](https://cloud.githubusercontent.com/assets/613617/6798049/a07982ce-d209-11e4-8bae-9b4b7a4f1ee1.png)

**Comment by danielgtaylor** [comment]
I've confirmed that this is working for me. Please re-open if it is still an issue with the latest versions.

**Comment by vinodc** [comment]
For anyone who stumbles on this:

I was encountering the same issue. It turned out I was using an out of date bootstrap mixins file with the latest version of aglio. If this is the case, you'd probably want the changes at lines [65](https://github.com/danielgtaylor/aglio/blob/master/templates/_bootstrap-mixins.jade#L65), [43](https://github.com/danielgtaylor/aglio/blob/master/templates/_bootstrap-mixins.jade#L43) and [91](https://github.com/danielgtaylor/aglio/blob/master/templates/_bootstrap-mixins.jade#L91) in your file to match the latest version.

**Comment by danielgtaylor** [comment]
@vinodc yep, unfortunately the AST format produced by the parser chanced, so these lines needed to be updated. I'm working with the API Blueprint team at Apiary to try and prevent such changes in the future.
